### ISSUE TITLE
Using SmoothOn Body double as alternative to Kwik-cast? 

### ISSUE THREAD

**Issue by SusanL82** [Coen-Lab/chronic-neuropixels#10]
Hello, 

Our local Czech WPI distributor does not sell Kwik-cast or Kwik-sil. 
Do you think we can use SmoothOn Body Double as an alternative for filling the gap at the bottom of the docking module? 
We've also considered using wax instead, but personally I worry about getting it on the probe and blocking all the contacts. Any ideas? 

Thanks, 
Susan

**Comment by cbimbo** [comment]
Hi Susan,

I would say that any soft-enough, biocompatible silicon should work. Hard to predict though, and I've never used SmoothOn Body Double. Maybe try with a dummy probe (or a glass pipette, or anything thin)? Otherwise some people put vaseline (heating it up a bit so that it's more fluid and easier to apply).
Also, we don't always put Kwik-sil at the bottom of the docking module (just duragel, then the shank are "in the air"). That could be an option?

Best,
Célian

**Comment by pipcoen** [comment]
Closing this issue for now, but can re-open if needed.
