### ISSUE TITLE
How does the NP2_PayloadLid (commercial) attach?

### ISSUE THREAD

**Issue by tofof** [Coen-Lab/chronic-neuropixels#14]
In the preprint, figure 6 A/F show how the 2.0alpha payload lid attaches to the assembly of the payload and docking modules. The 2.0 commercial's lid is a different design, and it's unclear exactly how it's intended to fit. 

Are any of the following correct? None seems completely correct.

![image](https://github.com/Coen-Lab/chronic-neuropixels/assets/3980843/055ad043-72d3-40ab-952e-49677473ce63)
![image](https://github.com/Coen-Lab/chronic-neuropixels/assets/3980843/7842ca3a-ec01-47df-ab1d-89ffadc1cc56)
![image](https://github.com/Coen-Lab/chronic-neuropixels/assets/3980843/8ee9e896-4ab2-4f1c-a89b-59bd36fbaeac)

 If not, is the lid itself the correct dimensions relative to the default 2.0 commercial parts?

**Comment by tofof** [comment]
After adding the GapBetweenModules to the constraint I put on inserting the probe holder into the docking module at the nose, the second arrangement gets better but still doesn't look quite right.

![image](https://github.com/Coen-Lab/chronic-neuropixels/assets/3980843/262b83b2-3ac7-400e-8465-0b930156f448)

**Comment by pipcoen** [comment]
Hiya. Thanks for bringing this up. 

Just fyi, there are pictures of the commercial assembly in the newly released [eLife preprint](https://elifesciences.org/reviewed-preprints/98522), Fig 1B. Your second image is correct. The reason it appears that there is a gap at the back is because there is a little "room to breathe" between the docking module and the payload. If you were to add a constraint that aligns the holes together of the two modules, you would see the gap is much-reduced (see image below). There is a small gap remaining to account for any issues with printing etc.

My advice would be to print the parts and assemble the first module without any probes to make sure everything fits together nicely. If there are any issues, please let me know! Closing this now, but feel free to re-open if my answer isn't clear.


![image](https://github.com/Coen-Lab/chronic-neuropixels/assets/1191043/39bb0013-0d16-4943-9121-29b8fe88c9e8)
